Repository spacetelescope/specviz, pull requests merged in 2018-10, with the labels that each got.

#455 Update MANIFEST.in and setup.py to install tracked files
  MANIFEST.in
  setup.py
Labels: bug

#509 Added a SpectralCoordinates class for glue plugin
  specviz/third_party/glue/tests/test_utils.py
  specviz/third_party/glue/utils.py
Labels: enhancement

#512 Baseline docs layout
  docs/_static/spec_icon.png
  docs/_static/specviz_logo.png
  docs/conf.py
  docs/getting-started.rst
  docs/index.rst
  docs/installation.rst
  docs/launching.rst
  docs/specviz/index.rst
Labels: documentation
